[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "animloid"
version = "2.7.0"
description = "Tarayıcı yok, reklam yok, dikkat dağıtıcı unsur yok. Sadece siz ve eşsiz bir anime izleme deneyimi."
readme = "README.md"
authors = [{ name = "RetakJunior", email = "retakjunior@users.noreply.github.com" }]
license = "CC-BY-NC-ND-4.0"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Environment :: Console",
]
keywords = ["anime", "animloid", "anime-download", "anime-watch", "anime-watching", "anime-downloading", "anime-cli", "allanime", "animecix", "anime-indir", "anime-izle", "anime-izleme", "anime-indirme", "tranime"]
requires-python = ">=3.8"
dependencies = [
    "typer[all]",
    "rich",
    "questionary",
    "requests",
    "packaging",
    "beautifulsoup4",
    "lxml",
    "pycryptodome",
    "curl_cffi",
    "appdirs",
    "prompt_toolkit>=3.0.36,<3.0.50",
    "pyfiglet",
    "py7zr",
    "pypresence",
    "winotify; sys_platform == 'win32'"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["weeb_cli*"]

[tool.setuptools.package-data]
weeb_cli = ["locales/*.json", "templates/*.html"]

[project.urls]
Homepage = "https://github.com/RetakJunior/AnimLoid"
Repository = "https://github.com/RetakJunior/AnimLoid"
Issues = "https://github.com/RetakJunior/AnimLoid/issues"

[project.scripts]
animloid = "weeb_app_entry:main"
